// <auto-generated />
using System;
using CBP.BemPatrimonial.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CBP.BemPatrimonial.API.Migrations
{
    [DbContext(typeof(PatrimonioContext))]
    partial class PatrimonioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.EstadoConservacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EstadoConservacao");
                });

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.Local", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.Patrimonio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CodigoDaBaixa")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoPatrimonio")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoPatrimonioCP")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataBaixa")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataDoacao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataEmprestimo")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataRetornoEmprestimo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataTransferencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("EstadoConservacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocalComplemento")
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NumeroNotaFiscal")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroProcessoBaixa")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PessoaResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorBem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CodigoPatrimonio")
                        .IsUnique()
                        .HasName("idx_bempatrimonial_patrimonio");

                    b.HasIndex("EstadoConservacaoId");

                    b.HasIndex("LocalId");

                    b.HasIndex("NumeroNotaFiscal")
                        .HasName("idx_bempatrimonial_numeronotafiscal");

                    b.HasIndex("PessoaResponsavelId");

                    b.ToTable("BemPatrimonial");
                });

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("LocaisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Matricula")
                        .HasColumnType("integer");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SegundoNome")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocaisId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.Patrimonio", b =>
                {
                    b.HasOne("CBP.BemPatrimonial.API.Models.EstadoConservacao", "EstadoConservacoes")
                        .WithMany("Patrimonios")
                        .HasForeignKey("EstadoConservacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CBP.BemPatrimonial.API.Models.Local", "Locais")
                        .WithMany("Patrimonios")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CBP.BemPatrimonial.API.Models.Pessoa", "PessoasResponsaveis")
                        .WithMany("Patrimonios")
                        .HasForeignKey("PessoaResponsavelId");
                });

            modelBuilder.Entity("CBP.BemPatrimonial.API.Models.Pessoa", b =>
                {
                    b.HasOne("CBP.BemPatrimonial.API.Models.Local", "Locais")
                        .WithMany("Pessoas")
                        .HasForeignKey("LocaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
