// <auto-generated />
using System;
using CBP.Transferencia.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CBP.Transferencia.API.Migrations
{
    [DbContext(typeof(TermoTransferenciaContext))]
    [Migration("20201228201125_AlteracaoCampoNomeParaDescricao")]
    partial class AlteracaoCampoNomeParaDescricao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CBP.Transferencia.API.Model.TermoTransferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVistoSetorDePatrimonio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("ResponsavelCedenteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelCedenteId")
                        .HasName("IDX_Cliente");

                    b.ToTable("TermoTransferencia");
                });

            modelBuilder.Entity("CBP.Transferencia.API.Model.TermoTransferenciaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroPatrimonio")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroPatrimonioCP")
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PatrimonioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("TermoTransferenciaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TermoTransferenciaId");

                    b.ToTable("TermoTransferenciaItens");
                });

            modelBuilder.Entity("CBP.Transferencia.API.Model.TermoTransferenciaItem", b =>
                {
                    b.HasOne("CBP.Transferencia.API.Model.TermoTransferencia", "TermoTransferencia")
                        .WithMany("Itens")
                        .HasForeignKey("TermoTransferenciaId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
